# Generated by Django 4.2.4 on 2023-08-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=20, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='問題文')),
                ('answer', models.CharField(max_length=128, verbose_name='正解')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='問題文')),
                ('answer', models.CharField(max_length=128, verbose_name='正解')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='問題文')),
                ('answer', models.CharField(max_length=128, verbose_name='正解')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='問題文')),
                ('answer', models.CharField(max_length=128, verbose_name='正解')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='問題文')),
                ('answer', models.CharField(max_length=128, verbose_name='正解')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('question_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Choice5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128, verbose_name='不正解1')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question5', verbose_name='問題文')),
            ],
        ),
        migrations.CreateModel(
            name='Choice4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128, verbose_name='不正解1')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question4', verbose_name='問題文')),
            ],
        ),
        migrations.CreateModel(
            name='Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128, verbose_name='不正解1')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question3', verbose_name='問題文')),
            ],
        ),
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128, verbose_name='不正解1')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question2', verbose_name='問題文')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=128, verbose_name='不正解1')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='問題文')),
            ],
        ),
    ]
